spring:
    application:
        name: yogerOrder

    datasource:
        url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        #show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        open-in-view: false

    threads:
        virtual:
            enabled: true

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            #password: ${REDIS_PASSWORD}

        mongodb:
            host: ${MONGO_HOST}
            port: ${MONGO_PORT}
            database: ${MONGO_DB_NAME}
            replica-set-name: rs0
            uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?replicaSet=rs0

portOne:
    v1:
        APIKey: ${V1_APIKEY}
        APISecret: ${V1_APISECRET}
    v2:
        APISecret: ${V2_APISECRET}

order:
    valid-time: 5
    cron:
        expiration: '0 0/1 * * * *'

product:
    url: ${PRODUCT_URL}

logging:
    level:
        org.library.yogerLibrary.log: DEBUG

management:
    endpoints:
        web:
            exposure:
                include: "*"
    metrics:
        enable:
            jvm: true

kafka:
    admin:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
        enable-idempotence: true
        transaction-id-prefix: tx-
    consumer:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
        auto-offset-reset: earliest
        enable-auto-commit: false
        isolation-level: read_committed
