spring:
    application:
        name: yogerOrder

    profiles:
        include: DB, portOne, service


cors:
    allowedOriginPatterns: '*'
    allowedHeaders: '*'
    allowedMethods: '*'

global:
    timeZone: 'Asia/Seoul'

logging:
    level:
        org.library.yogerLibrary.log: DEBUG