name: Bug Template
description: 버그 관련에 사용하는 템플릿
title: "[Bug] Bug Title"
projects: ["yoger's default project"]
labels: ["bug"]

body:
    - type: textarea
      id: bug-content
      attributes:
          label: Bug 설명
          description: 발생한 Bug에 대해 설명해주세요
          placeholder: ex) 트랜잭션 미적용
      validations:
          required: true
    - type: input
      id: related-issue
      attributes:
          label: 관련 Issue
          description: 관련된 Issue나 PR이 있다면 적어주세요.
          placeholder: "ex. #14"
      validations:
          required: false
    - type: textarea
      id: bug-fix-submissions
      attributes:
          label: 버그 수정 제안
          description: 버그 수정 제안 등이 있다면 적어주세요.
          placeholder: ex) @Transactional 적용
      validations:
          required: false
    - type: textarea
      id: etc
      attributes:
          label: 기타 사항
          description: 추가로 작성할 내용이 있다면 적어주세요.
          placeholder: 레퍼런스 링크, ... etc
      validations:
          required: false
