name: Refactor Template
description: 리팩토링 관련에 사용하는 템플릿
title: "[Refactor] Refactor Title"
projects: ["yoger's default project"]
labels: ["refactor"]

body:
    - type: textarea
      id: refactor-content
      attributes:
          label: 수정 사항 설명
          description: 수정할 작업에 대해 설명해주세요
          placeholder: ex) 코드 단순화
      validations:
          required: true
    - type: input
      id: related-issue
      attributes:
          label: 관련 Issue or PR
          description: 관련된 Issue나 PR이 있다면 적어주세요.
          placeholder: "ex. #14"
      validations:
          required: false
    - type: textarea
      id: etc
      attributes:
          label: 기타 사항
          description: 추가로 작성할 내용이 있다면 적어주세요.
          placeholder: 레퍼런스 링크, ... etc
      validations:
          required: false
